- name: Display all variables/facts known for a host
  ansible.builtin.debug:
    var: hostvars[inventory_hostname]
  tags: debug_info
  when: (debug.run is defined) and (debug.run|bool == true)

- name: Copy App Configuration
  ansible.builtin.template:
    src: configuration.yml
    dest: ~/ansible-playground/
